# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normal_horseshoe_cpp <- function(estimate, covmatrix, group_idx, numGroup, iterations, burnin, store, a1, a2, b1, a3, a4, b2, lambda2_fixed, lambda2_input, nugget) {
    .Call(`_shrinkem_normal_horseshoe_cpp`, estimate, covmatrix, group_idx, numGroup, iterations, burnin, store, a1, a2, b1, a3, a4, b2, lambda2_fixed, lambda2_input, nugget)
}

normal_lasso_cpp <- function(estimate, covmatrix, group_idx, numGroup, iterations, burnin, store, a1, a2, b1, lambda2_fixed, lambda2_input, nugget) {
    .Call(`_shrinkem_normal_lasso_cpp`, estimate, covmatrix, group_idx, numGroup, iterations, burnin, store, a1, a2, b1, lambda2_fixed, lambda2_input, nugget)
}

normal_ridge_cpp <- function(estimate, covmatrix, group_idx, numGroup, iterations, burnin, store, a1, a2, b1, lambda2_fixed, lambda2_input, nugget) {
    .Call(`_shrinkem_normal_ridge_cpp`, estimate, covmatrix, group_idx, numGroup, iterations, burnin, store, a1, a2, b1, lambda2_fixed, lambda2_input, nugget)
}

